services:
  # Main API Service
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      PORT: 4000
      DATABASE_URL: postgresql://pam_dev:dev_password@postgres:5432/pam_local
      REDIS_URL: redis://redis:6379
      JWT_SECRET: your-development-secret-key
      JWT_EXPIRES_IN: 24h
      REFRESH_TOKEN_EXPIRES_IN: 30d
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
      - redis

  # Client Application
  client:
    build:
      context: ./client
      target: development
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=/graphql
    depends_on:
      - api

  # Database
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: pam_dev
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: pam_local
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  # Cache
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # Database Admin
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@solidrust.net
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  # Redis Admin (Optional)
  redis-commander:
    image: rediscommander/redis-commander
    environment:
      REDIS_HOSTS: redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data: